log_iterations: 100
n_draws: 1000
batch_size: 150
checkpoint: /mnt/project/bio_embeddings/runs/hannes/protein-localization/runs/LightAttention_t5-encoderOnly_30-12_22-32-43

embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings/val_t5-encoderOnly.h5'
remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/fasta_files/val_as_per_deeploc.fasta'

