experiment_name: 'bertHALF'

num_epochs: 5000
batch_size: 150
log_iterations: 100
patience: 80
min_train_acc: 99.6
optimizer_parameters:
  lr: 5.0e-5

# Paths to Data
train_embeddings: 'data/embeddings/train_bertHALF.h5'
train_remapping: 'data/fasta_files/train.fasta'
val_embeddings: 'data/embeddings/val_bertHALF.h5'
val_remapping: 'data/fasta_files/val_homreduced.h5'
test_embeddings: 'data/embeddings/test_bertHALF.h5'
test_remapping: 'data/fasta_files/test_as_per_deeploc.fasta'
remapping_in_hash_format: False

# Model parameters
model_type: 'LightAttention'
model_parameters:
  dropout: 0.25
  kernel_size: 9
  output_dim: 10
