experiment_name: '9_Lr3e-5'

num_epochs: 5000
batch_size: 128
log_iterations: 100
solubility_loss: 0
optimizer_parameters:
  lr: 3.0e-5

# Paths to Data
train_embeddings: '/mnt/project/bio_embeddings/runs/hannes/embed_train/embeddings/bert_embeddings/embeddings_file.h5'
train_remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_train/embeddings/remapped_sequences_file.fasta'
val_embeddings: '/mnt/project/bio_embeddings/runs/hannes/embed_val/embeddings/bert_embeddings/embeddings_file.h5'
val_remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_val/embeddings/remapped_sequences_file.fasta'
test_embeddings: '/mnt/project/bio_embeddings/runs/hannes/embed_test/embeddings/bert_embeddings/embeddings_file.h5'
test_remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_test/embeddings/remapped_sequences_file.fasta'

# Model parameters
model_type: 'ConvMaxAvgPoolConv'
model_parameters:
  dropout: 0.25
  conv_dropout: 0.25
  kernel_size: 9
