log_iterations: 100
n_draws: 1000
batch_size: 150
checkpoint: /mnt/project/bio_embeddings/runs/hannes/protein-localization/runs/FirstAttention_solubilitylr1e-5_03-11_18-21-00

embeddings: '/mnt/project/bio_embeddings/runs/hannes/embed_test/embeddings/bert_embeddings/embeddings_file.h5'
remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_test/embeddings/remapped_sequences_file.fasta'

