log_iterations: 100
n_draws: 500
batch_size: 256
checkpoint: /mnt/project/bio_embeddings/runs/hannes/protein-localization/runs/FirstAttention_189_27-11_04-47-35

embeddings: '/mnt/project/bio_embeddings/runs/hannes/embed_test/embeddings/bert_embeddings/embeddings_file.h5'
remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_test/embeddings/remapped_sequences_file.fasta'

