log_iterations: 10
checkpoint: 'runs/ConvMaxAvgPoolConv_9_Lr3e-5_19-10_11-54-50'
batch_size: 128
embeddings: '/mnt/project/bio_embeddings/runs/hannes/embed_val/embeddings/bert_embeddings/embeddings_file.h5'
remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_val/embeddings/remapped_sequences_file.fasta'