log_iterations: 10
checkpoint: 'runs/ConvMaxAvgPool_9_replicate_19-10_10-02-20'
batch_size: 128
embeddings: '/mnt/project/bio_embeddings/runs/hannes/embed_val/embeddings/bert_embeddings/embeddings_file.h5'
remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_val/embeddings/remapped_sequences_file.fasta'