output_files_name: 'set_hard'

log_iterations: 100
n_draws: 1000
batch_size: 2
checkpoints_list:
  - runs/..finalModels/LightAttention__921_10-04_07-14-24





## T5 deeploc
#embeddings: 'data/embeddings/test_t5-encoderOnly.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#remapping_in_hash_format: False

## pssm deeploc
#embeddings: 'data/embeddings/subCell_all_pssmFile.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#remapping_in_hash_format: False

# pssm hard
#embeddings: 'data/embeddings/subCell_all_pssmFile.h5'
#remapping: 'data/embeddings/new_hard_set_t5_remapping.fasta'


# hard set
embeddings: 'data/embeddings_uniref50/new_hard_set.h5'
remapping: 'data/embeddings_uniref50/new_hard_set.fasta'
key_format: mheinzinger

#embeddings: 'data/embeddings/test_T5_reduced.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#remapping_in_hash_format: False

#embeddings: 'data/embeddings/new_hard_set_BERT_reduced.h5'
#remapping: data/embeddings/new_hard_set_BERT_remapping.fasta

#embeddings: 'data/embeddings/new_hard_set_t5.h5'
#remapping: 'data/embeddings/new_hard_set_t5_remapping.fasta'