output_files_name: 'set_hard'

log_iterations: 100
n_draws: 1000
batch_size: 2
checkpoints_list:
  - runs/..rebuttal/LightAttention_profiles_120_25-03_21-45-16
  - runs/..rebuttal/LightAttention_profiles_153_25-03_21-27-50
  - runs/..rebuttal/LightAttention_profiles_250_25-03_23-51-08
  - runs/..rebuttal/LightAttention_profiles_314_26-03_01-43-30
  - runs/..rebuttal/LightAttention_profiles_344_26-03_01-25-00
  - runs/..rebuttal/LightAttention_profiles_441_25-03_23-18-33
  - runs/..rebuttal/LightAttention_profiles_505_25-03_22-41-44
  - runs/..rebuttal/LightAttention_profiles_700_25-03_22-20-17
  - runs/..rebuttal/LightAttention_profiles_786_26-03_01-03-05
  - runs/..rebuttal/LightAttention_profiles_864_26-03_00-31-42

## T5 deeploc
#embeddings: 'data/embeddings/test_t5-encoderOnly.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#remapping_in_hash_format: False

## pssm deeploc
#embeddings: 'data/embeddings/subCell_all_pssmFile.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#remapping_in_hash_format: False

# pssm hard
embeddings: 'data/embeddings/subCell_all_pssmFile.h5'
remapping: 'data/embeddings/new_hard_set_t5_remapping.fasta'


#embeddings: 'data/embeddings/test_T5_reduced.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#remapping_in_hash_format: False

#embeddings: 'data/embeddings/new_hard_set_BERT_reduced.h5'
#remapping: data/embeddings/new_hard_set_BERT_remapping.fasta

#embeddings: 'data/embeddings/new_hard_set_t5.h5'
#remapping: 'data/embeddings/new_hard_set_t5_remapping.fasta'