output_files_name: 'deep_loc_test_set'

log_iterations: 100
n_draws: 1000
batch_size: 4
checkpoint: runs/..finalModels/LightAttentionMaxAblation__T5_976_24-01_05-56-20


embeddings: 'data/embeddings/test_t5-encoderOnly.h5'
remapping: data/fasta_files/test_as_per_deeploc.fasta
remapping_in_hash_format: False

#embeddings: 'data/embeddings/test_T5_reduced.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#remapping_in_hash_format: False

#embeddings: 'data/embeddings/new_hard_set_BERT_reduced.h5'
#remapping: data/embeddings/new_hard_set_BERT_remapping.fasta

#embeddings: 'data/embeddings/new_hard_set_t5.h5'
#remapping: 'data/embeddings/new_hard_set_t5_remapping.fasta'