output_files_name: 'deeploc_test_set'

log_iterations: 100
n_draws: 1000
batch_size: 4
checkpoint: runs/..finalModels/FFN__T5_976_21-01_12-30-12


embeddings: 'data/embeddings/test_T5_reduced.h5'
remapping: data/fasta_files/test_as_per_deeploc.fasta
remapping_in_hash_format: False

#embeddings: 'data/embeddings/new_hard_set_BERT.h5'
#remapping: data/embeddings/new_hard_set_BERT_remapping.fasta
