output_files_name: 'new_test_set'

log_iterations: 100
n_draws: 1000
batch_size: 4
checkpoint: runs/..finalModels/LightAttention_t5-encoderOnly_27-12_11-23-48

embeddings: data/embeddings/all_dupes_removesd_new_test_T5.h5
remapping: data/fasta_files/duplicates_removednew_test_set.fasta
