experiment_name: ''

num_epochs: 5000
batch_size: 2
log_iterations: 1
patience: 80
optimizer_parameters:
  lr: 5.0e-5

# Paths to Data
train_embeddings: 'data/embeddings/train.h5'
val_embeddings: 'data/embeddings/val.h5'
test_embeddings: 'data/embeddings/test.h5'
train_remapping: 'data/embeddings/train_remapped.fasta'
val_remapping: 'data/embeddings/val_remapped.fasta'
test_remapping: 'data/embeddings/test_remapped.fasta'

# Model parameters
model_type: 'LSTMConv'
model_parameters:
  output_dim: 10
  kernel_size: 9
  lstm_hidden_dim: 256
  n_layers: 2
  dropout: 0.2
