experiment_name: '9'

num_epochs: 5000
batch_size: 2
log_iterations: 10
solubility_loss: 0
optimizer_parameters:
  lr: 5.0e-6

# Paths to Data
train_embeddings: 'data/embeddings/train.h5'
val_embeddings: 'data/embeddings/val.h5'
test_embeddings: 'data/embeddings/test.h5'
train_remapping: 'data/embeddings/train_remapped.fasta'
val_remapping: 'data/embeddings/val_remapped.fasta'
test_remapping: 'data/embeddings/test_remapped.fasta'

#combined Data

# Model parameters
model_type: 'ConvsMaxAvgPool'
model_parameters:
  dropout: 0.25
