experiment_name: ''

num_epochs: 2500
batch_size: 2
log_iterations: 100
patience: 150
optimizer_parameters:
  lr: 5.0e-05

# Paths to Data
train_embeddings: 'data/embeddings/train.h5'
val_embeddings: 'data/embeddings/val.h5'
test_embeddings: 'data/embeddings/test.h5'
train_remapping: 'data/embeddings/train_remapped.fasta'
val_remapping: 'data/embeddings/val_remapped.fasta'
test_remapping: 'data/embeddings/test_remapped.fasta'

# Model parameters
model_type: 'ConvSmartPool'
model_parameters:
  output_dim: 10
  dropout: 0.25
  conv_dropout: 0.25
  kernel_size: 9
