experiment_name: '9_Lr3e-5'

num_epochs: 5000
batch_size: 4
log_iterations: 100
solubility_loss: 0
optimizer_parameters:
  lr: 3.0e-5

# Paths to Data
train_embeddings: 'data/embeddings/train.h5'
val_embeddings: 'data/embeddings/val.h5'
test_embeddings: 'data/embeddings/test.h5'
train_remapping: 'data/embeddings/train_remapped.fasta'
val_remapping: 'data/embeddings/val_remapped.fasta'
test_remapping: 'data/embeddings/test_remapped.fasta'

# Model parameters
model_type: 'ConvMaxAvgPoolConv'
model_parameters:
  dropout: 0.25
  conv_dropout: 0.25
  kernel_size: 9
