experiment_name: '9'

num_epochs: 5000
batch_size: 3
log_iterations: 100
optimizer_parameters:
  lr: 5.0e-5

# Paths to Data
train_embeddings: 'data/embeddings/train.h5'
val_embeddings: 'data/embeddings/val.h5'
test_embeddings: 'data/embeddings/test.h5'
train_remapping: 'data/embeddings/train_remapped.fasta'
val_remapping: 'data/embeddings/val_remapped.fasta'
test_remapping: 'data/embeddings/test_remapped.fasta'

# Model parameters
model_type: 'ConvMaxPool'
model_parameters:
  output_dim: 12
  dropout: 0.25
  conv_dropout: 0.25
  kernel_size: 9
