output_files_name: 'hard_set'

log_iterations: 100
n_draws: 1000
batch_size: 2
checkpoints_list:
  - runs/..Uniref50/FFN__279_12-04_12-52-12
  - runs/..Uniref50/FFN__303_12-04_11-49-15
  - runs/..Uniref50/FFN__309_12-04_10-36-49
  - runs/..Uniref50/FFN__451_12-04_12-24-07
  - runs/..Uniref50/FFN__559_12-04_11-18-35
  - runs/..Uniref50/FFN__624_12-04_13-40-04
  - runs/..Uniref50/FFN__657_12-04_14-26-15
  - runs/..Uniref50/FFN__702_12-04_14-53-34
  - runs/..Uniref50/FFN__921_12-04_09-31-41
  - runs/..Uniref50/FFN__969_12-04_10-03-45



#embeddings: 'data/embeddings/new_hard_set_BERT_reduced.h5'
#remapping: data/embeddings/new_hard_set_BERT_remapping.fastas

# pssm hard
#embeddings: 'data/embeddings/subCell_all_pssmFile.h5'
#remapping: 'data/embeddings/new_hard_set_t5_remapping.fasta'

#embeddings: 'data/embeddings/new_hard_set_t5.h5'
#remapping: 'data/embeddings/new_hard_set_t5_remapping.fasta'

## deeploc UNIREF50
#embeddings: 'data/embeddings_uniref50/new_hard_set.h5'
#remapping: 'data/embeddings_uniref50/new_hard_set.fasta'
#key_format: mheinzinger

# deeploc UNIREF50 POOLeD
embeddings: 'data/uniref_embeddings_pooled/new_hard_set.h5'
remapping: 'data/uniref_embeddings_pooled/new_hard_set.fasta'
key_format: mheinzinger


