output_files_name: 'inference_on_deeploc_test'

log_iterations: 100
n_draws: 1000
batch_size: 2
checkpoints_list:
  - runs/..Uniref50/LightAttention__559_13-04_00-55-46


embeddings: 'data/uniref_embeddings_from_pipeline/embeddings_file.h5'
remapping: 'data/uniref_embeddings_from_pipeline/remapped_sequences_file.fasta'



