output_files_name: 'inference_on_deeploc_test'

log_iterations: 100
n_draws: 1000
batch_size: 2
checkpoints_list:
  - runs/LightAttention__11-04_18-55-27


embeddings: 'data/embeddings/test_as_per_deeploc.h5'
remapping: 'data/embeddings/test_as_per_deeploc.fasta'



