output_files_name: 'deeploc_test_set'

log_iterations: 100
n_draws: 1000
batch_size: 1
checkpoint: runs/..finalModels/LightAttention_t5-encoderOnly_22-12_18-35-28

#embeddings: 'data/embeddings/test_t5-encoderOnly.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#key_format: mheinzinger_old

#embeddings: 'data/embeddings/test_T5_reduced.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#key_format: mheinzinger_old

#embeddings: 'data/embeddings/new_hard_set_BERT.h5'
#remapping: data/embeddings/new_hard_set_BERT_remapping.fasta
