output_files_name: 'deeploc_test'

log_iterations: 100
n_draws: 1000
batch_size: 2
checkpoints_list:
  - runs/..Uniref50/BahdanauAttention__309_13-04_12-11-13
  - runs/..Uniref50/BahdanauAttention__921_12-04_22-00-55
  - runs/..Uniref50/BahdanauAttention__969_13-04_07-54-00
  - runs/..Uniref50/BahdanauAttention_bahdanau_attention_13-04_18-49-34
  - runs/..Uniref50/BahdanauAttention_bahdanau_attention_13-04_21-00-13
  - runs/..Uniref50/BahdanauAttention_bahdanau_attention_14-04_02-30-08
  - runs/..Uniref50/BahdanauAttention_bahdanau_attention_14-04_09-51-51
  - runs/..Uniref50/BahdanauAttention_bahdanau_attention_14-04_13-26-05
  - runs/..Uniref50/BahdanauAttention_bahdanau_attention_14-04_16-00-48
  - runs/..Uniref50/BahdanauAttention_bahdanau_attention_15-04_07-24-11





## T5 deeploc
#embeddings: 'data/embeddings/test_t5-encoderOnly.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#remapping_in_hash_format: False

## pssm deeploc
#embeddings: 'data/embeddings/subCell_all_pssmFile.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#remapping_in_hash_format: False


# deeploc UNIREF50
embeddings: 'data/embeddings_uniref50/test_as_per_deeploc.h5'
remapping: 'data/embeddings_uniref50/test_as_per_deeploc.fasta'
key_format: mheinzinger

## deeploc UNIREF50 POOLeD
#embeddings: 'data/uniref_embeddings_pooled/test_as_per_deeploc.h5'
#remapping: 'data/uniref_embeddings_pooled/test_as_per_deeploc.fasta'
#key_format: mheinzinger

