output_files_name: 'new_hard_set'

log_iterations: 100
n_draws: 1000
batch_size: 4
checkpoint: runs/..finalModels/FirstAttention_927_15-11_08-38-57

embeddings: 'data/embeddings/new_hard_set_BERT.h5'
remapping: data/embeddings/new_hard_set_BERT_remapping.fasta
