output_files_name: 'inference_on_setHARD'

log_iterations: 100
n_draws: 1000
batch_size: 6
checkpoints_list:
  - runs/LightAttention_localization_prediction_esmb1_02-09_15-40-51


embeddings: 'data/test_esmb1.h5'
remapping: 'data/test_esmb1.h5'
key_format: hash



