experiment_name: ''

num_epochs: 5000
batch_size: 2
log_iterations: 100
patience: 80
min_train_acc: 99.6
optimizer_parameters:
  lr: 5.0e-5

# Paths to Data
train_embeddings: 'data/uniref_embeddings/train.h5'
val_embeddings: 'data/uniref_embeddings/val_homreduced.h5'
test_embeddings: 'data/uniref_embeddings/test_as_per_deeploc.h5'
train_remapping: 'data/uniref_embeddings/train.fasta'
val_remapping: 'data/uniref_embeddings/val_homreduced.fasta'
test_remapping: 'data/uniref_embeddings/test_as_per_deeploc.fasta'
key_format: 'mheinzinger'

# Model parameters
model_type: 'FFN'
model_parameters:
  output_dim: 10
  hidden_dim: 32
  n_hidden_layers: 0
  dropout: 0.25
