eval_on_test: True
num_epochs: 5000
batch_size: 1024
log_iterations: 100
patience: 100
max_length: 13000
optimizer_parameters:
  lr: 1.0e-4

# Paths to Data
train_embeddings: 'data/embeddings/train_T5_reduced.h5'
train_remapping: 'data/fasta_files/train.fasta'
val_embeddings: 'data/embeddings/val_T5_reduced.h5'
val_remapping: 'data/fasta_files/val_homreduced.fasta'
test_embeddings: 'data/embeddings/test_T5_reduced.h5'
test_remapping: 'data/fasta_files/test_as_per_deeploc.fasta'
key_format: mheinzinger_old

# Model parameters
model_type: 'FFN'
model_parameters:
  output_dim: 10
  hidden_dim: 32
  n_hidden_layers: 0
  dropout: 0.25
