experiment_name: ''

num_epochs: 10000
batch_size: 2
log_iterations: 2
solubility_loss: 0
optimizer_parameters:
  lr: 1.0e-4
#checkpoint: 'runs/max_avg_dropout05_27-09_08-49-02'

# Paths to Data
train_embeddings: 'data/embeddings/train.h5'
val_embeddings: 'data/embeddings/val.h5'
test_embeddings: 'data/embeddings/test.h5'
train_remapping: 'data/embeddings/train_remapped.fasta'
val_remapping: 'data/embeddings/val_remapped.fasta'
test_remapping: 'data/embeddings/test_remapped.fasta'

# Model parameters
model_type: 'LSTMConvs'
model_parameters:
  output_dim: 12
  lstm_hidden_dim: 32
  n_layers: 2
  dropout: 0.25
