experiment_name: ''

num_epochs: 5000
batch_size: 2
lrate: 5.0e-5
log_iterations: 5

# Paths to Data
train_embeddings: 'data/embeddings/train.h5'
train_remapping: 'data/embeddings/train_remapped.fasta'
val_embeddings: 'data/embeddings/val.h5'
val_remapping: 'data/embeddings/val_remapped.fasta'
test_embeddings: 'data/embeddings/test.h5'
test_remapping: 'data/embeddings/test_remapped.fasta'

# Model parameters
model_type: 'SelfAttentionMaxAvgPool' # the actual name of the class of the model that should be used
model_parameters:
  dropout: 0.25
  attention_dropout: 0.25
  n_heads: 8
