experiment_name: 'deeper_network'

num_epochs: 5000
batch_size: 2048
lrate: 1.0e-4

# Paths to Data
train_embeddings: 'data/embeddings/train_reduced.h5'
train_remapping: 'data/embeddings/train_remapped.fasta'
val_embeddings: 'data/embeddings/val_reduced.h5'
val_remapping: 'data/embeddings/val_remapped.fasta'
test_embeddings: 'data/embeddings/test_reduced.h5'
test_remapping: 'data/embeddings/test_remapped.fasta'

# Model parameters
model_type: 'fixed-length'
hidden_dim: 64
num_hidden_layers: 1
dropout: 0.25